
build:
	echo "running build..."
	npm run build
synth:
	cdk synth --all
diff:
	cdk diff
watch:
	echo "running watch..."
	npm run watch
test: 
	echo "running unit tests..."
	npm run test
deploy-vpc:
	echo "deploying vpc stack..."
	cdk deploy dp-base-stack
deploy-iam:
	echo "deploying iam stack..."
deploy-ec2:
	echo "deploying ec2 stack..."
deploy-s3:
	echo "deploying s3 stack..."
deploy-redshift:
	echo "deploying redshift stack..."
